site_name: KillThisSE Docs

nav:
  - Whatever: api.md
  - Home
    - abc: api.md
    - bcd: modules.md

theme:
  name: material
  language: zh

  custom_dir: theme/

plugins:
  - search
  - git-authors